### ISSUE TITLE
나눔 펜 스크립트

### ISSUE THREAD

**Issue by darron1217** [gshn/fonts#1]
나눔 펜 공식 이름이 Nanum Pen Script 인것으로 알고있는데

버전이 다른건가요? 이름은 공식명칭으로 되면 더 좋을것 같습니다 :)

https://fonts.google.com/specimen/Nanum+Pen+Script
이거랑 같은 폰트가 맞는지 확인부탁드립니다

**Comment by gshn** [comment]
네이버 배포판 공식 명칭은 '나눔손글씨 펜체' 에 'NanumPen' 으로 배포되고 있습니다.
아마 구글에서 배포하는 폰트와 일치 할 것으로 예상됩니다만, 공식 배포판의 규칙을 따르도록 하겠습니다.
